#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

controller:
  # -- Number of pods to load balance between
  replicas: 1

image:
  # -- image repository
  repository: ghcr.io/ajvpot/vanderbot/vanderbot
  # -- image tag
  tag: latest@sha256:0f1f080f37725c7aa4bd40190585a35ed536a563eef82429393ddffb11b10929
  # -- image pull policy
  pullPolicy: Always

# -- environment variables. See more environment variables in the [nullserv documentation](https://github.com/bmrzycki/nullserv/blob/master/README.md).
# @default -- See below
env:
  # -- Set the container timezone
  TZ: UTC

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

# -- Configures the probes for the main Pod.
# @default -- See values.yaml
probes:
  readiness:
    #enabled: true
    #custom: true
    spec:
      httpGet:
        path: /welcome.txt
        port: http

service:
  main:
    enabled: false
    primary: true
    type: NodePort
    ports:
      http:
        port: 80
      https:
        enabled: true
        port: 443
