#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

controller:
  # -- Number of pods to load balance between
  replicas: 1

image:
  # -- image repository
  repository: ghcr.io/ajvpot/vanderbot/vanderbot-2946d9cdf8c6625ee0d8369a54877e5f
  # -- image tag
  tag: latest@sha256:f470d4b131b95c8aba3f7fa5b2bb5040724237464aab2053e564504f89292fbe
  # -- image pull policy
  pullPolicy: Always

# -- environment variables. See more environment variables in the [nullserv documentation](https://github.com/bmrzycki/nullserv/blob/master/README.md).
# @default -- See below
env:
  # -- Set the container timezone
  TZ: UTC
  DATABASE_URL: "postgres://postgres:postgres@{{ printf \"%s-postgresql\" .Release.Name }}:5432/vanderbot?sslmode=disable"

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

# -- Configures the probes for the main Pod.
# @default -- See values.yaml
probes:
  readiness:
    enabled: false
  liveness:
    enabled: false
  startup:
    enabled: false


service:
  main:
    enabled: true
    primary: true
    type: ClusterIP
    ports:
      http:
        enabled: true
        primary: false
        port: 80
      system:
        enabled: true
        port: 8392


# -- Bitnami postgres chart. For more options see https://github.com/bitnami/charts/tree/master/bitnami/postgresql
# @default -- see below
postgresql:
  # -- By default uses an internal postgres. Disable if you use your own Postgres.
  enabled: true
  auth:
    postgresPassword: postgres
    database: vanderbot
  persistence:
    # -- if database is stored to a PVC. Set to true when you are done testing.
    enabled: false
    # storageClass: ""